[project]
name = "hub-platform"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.30.0",
    "eventry>=0.6.0",
    "fluent-runtime>=0.4.0",
    "pyconfigtree>=0.2.2",
    "pydantic>=2.13.4",
]

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "ruff>=0.16.2",
]


[tool.tox]
env_list = ['3.14', '3.15']


[tool.pytest]
markers = [
    "slow: long-running tests",
]


[tool.tox.env_run_base]
deps = ["pytest", "pytest-asyncio", "mypy"]
commands = [
    ["pytest", "--basetemp={env_tmp_dir}", { replace = "posargs", default = ["tests"], extend = true }],
    ["mypy", {replace = "posargs", default = ["."], extend = true}]
]


[tool.mypy]
python_version = '3.14'
warn_redundant_casts = true
warn_unused_ignores = true
strict = true
pretty = true
files = ["hubplatform", "tests"]


[tool.ruff]
line-length = 99
include = [
    'hubplatform/**/*.py',
    'tests/**/*.py'
]


[tool.ruff.format]
quote-style = "single"
line-ending = "lf"
indent-style = "space"
docstring-code-format = true


[tool.ruff.lint]
select = [
    "I",
    "N",
    "C4",
    "E",
    "F",
    "T20",
    "RET",
]
extend-select = ["D212"]


[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
required-imports = ["from __future__ import annotations"]
force-to-top = ["typing", "dataclasses"]
length-sort = true
lines-between-types = 0
lines-after-imports = 2
split-on-trailing-comma = true
combine-as-imports = true

